### ISSUE TITLE
Shouldn't be parse("Sep 2003") an interval?  

### ISSUE THREAD

**Issue by trikko** [JackStouffer/date-parser#10] opened 2016-05-31 15:01 UTC
Sep 2003 sounds more like  (1 september -> 30 september 2003) rather than 1 september 2003.

Maybe everything should be parsed as interval   2003/09/01 ==> ( 2003/09/01 00:00:00.0000  2003/09/01 23:59:59.9999) . Maybe a [) interval works better.

Then from code you can ignore interval and take only interval begin if it's ok for you.

Instead of an interval a  couple  date, duration can be used too.

**Comment by JackStouffer** [comment] 2016-05-31 15:14
This is by design, as the current API relies on `defaultDate`; any information you provide is applied on top of `defaultDate`.

This allows for usages like 

```
parse("10:00 AM", No.ignoreTimezone, null, No.dayFirst, No.yearFirst, No.fuzzy, Clock.currTime)
```

which is very useful when parsing things like messages.

**Comment by trikko** [comment] 2016-05-31 16:04
Maybe another function to parse as interval could be useful.

**Comment by JackStouffer** [comment] 2016-08-19 19:08
As this was originally posed as a question about the API of `parse`, I will close this as that question has been answered.

For tracking the issue of parsing intervals with a _different function_, I will use #11.

**Closed as completed by JackStouffer** 2016-08-19 19:08 UTC
Labels: question
